
export { default as PostgreSQLSVG } from './postgresql.jsx'
export { default as ReactSVG } from './react.jsx'
export { default as ReduxSVG } from './redux.jsx'
export { default as MongoSVG } from './mongo.jsx'
export { default as WebpackSVG } from './webpack.jsx'
export { default as JavascriptSVG } from './javascript.jsx'
export { default as NodeSVG } from './node.jsx'
export { default as FeathersSVG } from './feathersSVG.jsx'
export { default as JavaSVG } from './java.jsx'
export { default as SwiftSVG } from './swift.jsx'